### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by nvmnghia** [Ademking/fb-profile-picture-viewer#4]
The script searches for `owner_id` in the HTML returned from mbasic site. Currently, mbasic site doesn't have such information anymore, that's why the script fails in the first place.
I guess that `owner_id` is the profile ID given to each profile before they choose their own name, and confirm this is true: I got my jumbo size avatar right away. So the fix is to find another way to obtain `owner_id`.

**Comment by Ademking** [comment]
Hello @nvmnghia,
It's working fine (March 30, 2021)
I've test it and there is no error...

**Comment by nvmnghia** [comment]
Yes it seems to be working fine lmao. I tried another account and voila. Maybe they blocked me for abuse      your extension. Thanks for the great work!
