### ISSUE TITLE
Ver 1.03 of plugin no longer works

### ISSUE THREAD

**Issue by beevista** [Ademking/fb-profile-picture-viewer#5]
Error message: "Could not extract Facebook Profile Picture".

Replicated with various browsers, and when both logged out and logged in.

P.S: It was working yesterday (at the time of this posting), doesn't work now.

**Comment by Ademking** [comment]
@beevista It's working fine for me... 04/03/2021
Try to install the extension again and check if the url is correct

**Comment by beevista** [comment]
Reinstalled the plugin. It's not working for me. I also tested on various URLs.

I clicked 'Unlock full size profile picture' and 'Could not extract Facebook Profile Picture' error is displayed.

![1](https://user-images.githubusercontent.com/81862227/113480166-a43f1d80-94c5-11eb-912f-8b404bc7d6c2.png)
![2](https://user-images.githubusercontent.com/81862227/113480167-a73a0e00-94c5-11eb-9cbc-1b0c65d73064.png)

**Comment by beevista** [comment]
I am wondering... could it be Facebook had done updates on its side that broke the plugin?

Or maybe I was blocked (IP blocked?). But it was working okay yesterday, and I wasn't signed in to Facebook.

**Comment by beevista** [comment]
Dear dev, I found out that the plugin works!

You have to sign in to Facebook now. Previously (yesterday), that was optional. The plugin worked even if you didn't sign in to Facebook. Facebook must have made some updates on its side.

Facebook (including Instagram that it owns) does not like third party apps and plugins that bypass its restrictions. They constantly break third party stuff.

Thank you for your work. Peace out.

**Comment by Ademking** [comment]
> Dear dev, I found out that the plugin works!
> 
> You have to sign in to Facebook now. Previously (yesterday), that was optional. The plugin worked even if you didn't sign in to Facebook. Facebook must have made some updates on its side.
> 
> Facebook (including Instagram that it owns) does not like third party apps and plugins that bypass its restrictions. They constantly break third party stuff.
> 
> Thank you for your work. Peace out.

@beevista Thank you so much for your information. I didn't know that you need to be signed in to facebook.. 
Facebook is constantly breaking every third party apps/pluggins.
Thank you again for your time and effort.
